name: Secrets (detect-secrets)

on: [workflow_dispatch, workflow_call]

jobs:
    SCI012-Secrets:
        name: Analyzing for Secrets

        permissions:
            actions: read # for actions/checkout to fetch code
            contents: read # for actions/checkout to fetch code
            pull-requests: read

        runs-on: ubuntu-latest

        steps:
        - name: Checkout Source Code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'

        - name: installing `detect-secrets`
          run: pip install detect-secrets==1.5.0

        - name: scanning repository
          run: detect-secrets scan --all-files > .secrets.baseline

        - name: creating report
          run: detect-secrets audit --report --json .secrets.baseline > report.json

        - name: creating baseline.json
          run: cp .secrets.baseline baseline.json

        - name: Run Python script
          run: |
            python .github/scripts/sarif.py  # Replace with the path to your Python file

        - name: know more
          run: ls -a


        - name: Upload json report as Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: sarif-reports
            path: |
              ./report.json
              ./baseline.json
            retention-days: 1

        # - name: Upload SARIF Report to Security Tab
        #   uses: github/codeql-action/upload-sarif@v3
        #   with:
        #     sarif_file: report.sarif
