name: Secrets (detect-secrets)

on: [push, pull_request, workflow_dispatch, workflow_call]

jobs:
    SCI012-Secrets:
        name: Analyzing for Secrets

        permissions:
            actions: read # for actions/checkout to fetch code
            contents: read # for actions/checkout to fetch code
            pull-requests: read

        runs-on: ubuntu-latest

        steps:
        - name: Checkout Source Code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'

        - name: installing `detect-secrets`
          run: pip install detect-secrets==1.5.0

        - name: scanning repository
          run: detect-secrets scan -- all-files > .secrets.baseline

        - name: creating report
          run: detect-secrets audit --report --json .secrets.baseline > report.json

        - name: Upload report Artifact
          uses: actions/upload-artifact@v4
          with:
            name: report.json
            path: ./report.json
            retention-days: 2
