name: Secrets

on: [ workflow_call ]

jobs:
    SCI012-Secrets:
        name: Analyzing for Secrets

        permissions:
            actions: read # for actions/checkout to fetch code
            contents: read # for actions/checkout to fetch code
            pull-requests: read
            security-events: write

        runs-on: ubuntu-latest

        env:
          SCRIPT_PATH: ".github/scripts/Secrets"

        steps:
        - name: Checkout Source Code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'

        - name: installing `detect-secrets`
          run: pip install detect-secrets==1.5.0

        - name: scanning repository
          run: detect-secrets scan --all-files --exclude-files ".git" > .secrets.baseline

        - name: creating report
          run: detect-secrets audit --report --json .secrets.baseline > report.json

        - name: Checking Secrets Script
          uses: actions/checkout@v4
          with:
            repository: "ethicalakhilesh/ESCROW"
            path: ${{ env.SCRIPT_PATH }}
            ref: "main"
            sparse-checkout: |
              sarif-generator.py
            sparse-checkout-cone-mode: false
        
        - name: Generating SARIF Report
          run: |
            ls -a ".github/scripts/Secrets/.github/scripts/Secrets" 
            cp ${{ env.SCRIPT_PATH }}/${{ env.SCRIPT_PATH }}/sarif-generator.py .
            python sarif-generator.py

        - name: Upload SARIF Report to Security Tab
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: results.sarif