name: Sarif Upload

on:
  workflow_dispatch:

jobs:
  upload-sarif:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload SARIF Report to Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sample.sarif

      - name: Upload sarif as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sarif-reports
          path: |
            ./sample.sarif
